export const SET_ALL_50_STATES = "SET_ALL_50_STATES";
export const SET_ALL_PARKS_DATA = "SET_ALL_PARKS_DATA";
export const SET_STATE_CHOSEN_ABREV = "SET_STATE_CHOSEN_ABREV";
export const SET_ALL_PARKS_WITHIN_STATE = "SET_ALL_PARKS_WITHIN-STATE";
export const SET_PARK_CHOSEN_PARK_CODE = "SET_PARK_CHOSEN_PARK_CODE";
export const SET_PARK_OPTION_INDEX_SELECTED = "SET_PARK_OPTION_INDEX_SELECTED";
export const SET_PARK_CHOSEN_DATA = "SET_PARK_CHOSEN_DATA";
